# Generated by Django 2.2.6 on 2023-02-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20230131_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='music.Author', verbose_name='укажите автора песни'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='music.Genre', verbose_name='укажите жанр песни'),
        ),
        migrations.AlterField(
            model_name='music',
            name='text',
            field=models.TextField(help_text='Введите текст песни', verbose_name='текст песги'),
        ),
    ]
