# Generated by Django 2.2.6 on 2023-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20230201_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='translation',
            field=models.TextField(blank=True, help_text='Если песня не на русском языке', verbose_name='перевод песни'),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.TextField(verbose_name='название песни'),
        ),
        migrations.AlterField(
            model_name='music',
            name='text',
            field=models.TextField(help_text='Введите текст песни', verbose_name='текст песни'),
        ),
    ]
