# Generated by Django 2.2.6 on 2023-02-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20230201_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
