# Generated by Django 2.2.6 on 2023-02-01 11:38

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='music.Author', verbose_name='автор песни'),
        ),
        migrations.AlterField(
            model_name='music',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
