# Generated by Django 2.2.6 on 2023-02-02 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0006_auto_20230201_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to=settings.AUTH_USER_MODEL, verbose_name='пользавотель'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='music.Genre', verbose_name='жанр песни'),
        ),
        migrations.AlterField(
            model_name='music',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='music',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Ссылка на видео. Желательно Youtube.        Не все видео могут отображаться на сайте, из-за авторских прав', verbose_name='видео'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст комментария', verbose_name='текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.Music')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
